FROM nbattala/jmeter:5.5
MAINTAINER naveen battala<nbattala@gmail.com>

EXPOSE 1099

ENTRYPOINT $JMETER_HOME/bin/jmeter-server \
-Dserver.rmi.localport=1099 \
-Dserver_port=1099 \
-Jserver.rmi.ssl.disable=true
