apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter
  labels:
    #do not change this label as it is used in load_test.sh to find namespace of jmeter pod
    app: jmeter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmeter
  template:
    metadata:
      labels:
        app: jmeter
    spec:
      tolerations:
      - effect: NoSchedule
        key: workload/class
        operator: Equal
        value: loadtest
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: workload/class
                operator: In
                values:
                  - loadtest
      containers:
      - name: jmeter
        image: nbattala/jmeter:5.5
        imagePullPolicy: Always
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
          - name: loadtest
            mountPath: /load_test
            subPath: "load_test"
        ports:
        - containerPort: 60000
        resources:
          limits:
            cpu: "4"
            memory: 8000Mi
          requests:
            cpu: "1"
            memory: 500Mi
      volumes:
      - name: loadtest 
        configMap:
         name: jmeter-cm
